# Generated by Django 6.0.2 on 2026-03-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_chainofcustody'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='blockchain_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caselog',
            name='blockchain_hash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='caselog',
            name='blockchain_tx',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caselog',
            name='blockchain_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
