# Generated by Django 6.0.2 on 2026-03-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caselog_blockchain_block_caselog_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='blockchain_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='blockchain_hash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='blockchain_tx',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='blockchain_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
