# Generated by Django 6.0.2 on 2026-03-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_chainofcustody_blockchain_block_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='blockchain_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='blockchain_hash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='blockchain_tx',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='blockchain_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CaseHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_officer_username', models.CharField(blank=True, default='', max_length=150)),
                ('to_officer_username', models.CharField(blank=True, default='', max_length=150)),
                ('crime_number', models.CharField(blank=True, default='', max_length=100)),
                ('blockchain_tx', models.CharField(blank=True, default='', max_length=200)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=100)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('blockchain_url', models.URLField(blank=True, default='')),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_authorized', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='cases.case')),
                ('from_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('to_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('further_action', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_tx', models.CharField(blank=True, default='', max_length=200)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=100)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('blockchain_url', models.URLField(blank=True, default='')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='cases.case')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
