# Generated by Django 6.0.2 on 2026-03-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_blockchain_block_case_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseprogress',
            options={'ordering': ['-date_of_progress']},
        ),
        migrations.RenameField(
            model_name='caseprogress',
            old_name='date',
            new_name='date_of_progress',
        ),
    ]
