# Generated by Django 6.0.2 on 2026-03-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_caseprogress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseprogress',
            old_name='details',
            new_name='details_of_progress',
        ),
        migrations.RenameField(
            model_name='caseprogress',
            old_name='further_action',
            new_name='further_action_to_be_taken',
        ),
    ]
