# Generated by Django 6.0.2 on 2026-03-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_rename_details_caseprogress_details_of_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseprogress',
            name='added_by',
        ),
        migrations.AddField(
            model_name='caseprogress',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_progress_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
