# Generated by Django 6.0.2 on 2026-04-01 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_caseprogress_added_by_caseprogress_officer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PDF', 'PDF Document'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('file_size', models.IntegerField(default=0)),
                ('file_hash', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('blockchain_tx', models.CharField(blank=True, default='', max_length=200)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=100)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('blockchain_url', models.URLField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('statement', models.TextField(blank=True, default='')),
                ('is_hostile', models.BooleanField(default=False)),
                ('is_section_164', models.BooleanField(default=False)),
                ('protection_status', models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('ACTIVE', 'Active')], default='NONE', max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_tx', models.CharField(blank=True, default='', max_length=200)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=100)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('blockchain_url', models.URLField(blank=True, default='')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_witnesses', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.case')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
