# Generated by Django 6.0.2 on 2026-04-01 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_evidence_witness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderThreatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('reasons', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insider Threat Alert',
                'verbose_name_plural': '🚨 Insider Threat Alerts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
