# Generated by Django 6.0.2 on 2026-04-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_insiderthreatalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsiderThreatAlert',
        ),
    ]
