# Generated by Django 6.0.2 on 2026-03-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('blockchain_tx', models.CharField(blank=True, default='', max_length=200)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=100)),
                ('blockchain_block', models.IntegerField(blank=True, null=True)),
                ('blockchain_url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
