# Generated by Django 6.0.2 on 2026-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_security_answer_1_user_security_answer_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(max_length=255),
        ),
    ]
