# Generated by Django 6.0.2 on 2026-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
