# Generated by Django 6.0.2 on 2026-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
