# Generated by Django 6.0.2 on 2026-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_google_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
